seatrac_udp_node:
  ros__parameters:

    # ------------------------------------------------------------
    # Transport
    # ------------------------------------------------------------
    transport: "udp"
    blueos_ip: "192.168.2.3"
    blueos_port: 15000
    response_timeout_s: 3.0

    # ------------------------------------------------------------
    # Environment - Sea water
    # ------------------------------------------------------------
    salinity_ppt: 35.0
    auto_vos: true
    auto_pressure_offset: true

    # ------------------------------------------------------------
    # Acquisition
    # ------------------------------------------------------------
    status_rate_hz: 1.0
    allow_persistent_save: false

    # ------------------------------------------------------------
    # Acoustic positioning
    # ------------------------------------------------------------
    acoustic_positioning_enabled: false
